running go version instead of failure

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -17,6 +17,10 @@ jobs:
         uses: actions/setup-go@v5
         with:
           go-version: '1.22'
+      
+      - name: Print Go Version
+        uses: actions/setup-go@v5
+        run: go version 
 
-      - name: Force Failure
-        run: (exit 1)
+      #- name: Force Failure
+      #  run: (exit 1)
